TESTS = [
    ('A', True),
    ('T', True),
    ('.L', True),
    ('(!A)', True),
    ('(A&B)', True),
    ('(A&(!B))', True),
    ('((!A)&(!B))', True),
    ('((A&((!B)&(!C))) | ((!D)&(E&F)))', True),
    ('((A&B) | C)', True),
    ('(A|B)', True),
    ('(A|(B&(C|D)))', False),
    ("((a | b))", True),
    ("((a & b))", True),
    ("(((a | b) | c))", True),
    ("(((a & b) & c))", True),
    ("((a | (b | c)))", True),
    ("((a & (b & c)))", True),
    ('(!(A|B))', False),
    ('(!(A&B))', False),
    ("((a | b) & !(a & b))", False),
    ("((a | b) & (c & d))", False),
    ("(((a | b) & c) | (d & e))", False),
]
