@startuml

class Аукционная_Платформа {
  - Лоты: Лоты
  - Покупатели: Покупатели
  - Продавцы: Продавцы
  - Сервис_Аутентификации: Сервис_Аутентификации
  - Платежный_Сервис: Платежный_Сервис
  - Статистический_Сервис: Статистический_Сервис
}

class Лоты {
    - лоты:
    + Просмотреть_Лоты()
    + Добавить_Лот(лот)
    + Редактировать_Лот(лот)
    + Деактивировать_Лот(лот)
    + Сделать_Ставку(лот, ставка)
    + Определить_Победителя(лот)
}

class Сервис_Аутентификации {
    - пользователи
    + войти(логин, пароль)
}

class Статистический_Сервис {
    подвести_Статистику()
}

class Платежный_Сервис {
    + пополнить(покупатель, сумма пополнения)
    + снять(продавец, сумма снятия)
}

class Покупатели {
    - покупатели
    + Просмотреть_Продавцов()
    + Добавить_Покупателя(Покупатель: Покупатель)
    + Редактировать_Покупателя(Покупатель: Покупатель)
    + История_Ставок(Покупатель: Покупатель)
    + История_Покупок(Покупатель: Покупатель)
}

class Продавцы {
    - продавцы
  
    + Посмотреть_Список_Продавцов()
    + Добавить_Продавца(Продавец)
    + Редактировать_Продавца(Продавец)
    + Просмотреть_историю_лотов(Продавец)
    + Просмотреть_история_продаж(Продавец)
    + Добавить_отзыв(Продавец, отзыв)
}

class Покупатель {
  - ФИО
  - баланс
  - адрес_доставки
  - ставки
  - покупки
}

class Продавец {
  - ФИО
  - баланс
  - адрес_забора
  - лоты
  - рейтинг
  - отзывы
}

class Лот {
  - название
  - описание
  - стартовая_цена
  - шаг_ставки
  - ставки
  - победившая ставка
  - статус
}

class Ставка {
  - покупатель
  - сумма
}


class Отзыв {
  - Продавец
  - рейтинг
  - текст
}

class User {
    логин
    пароль
}

' Композиция
Покупатели "1" *-- "0..*" Покупатель
Продавцы "1" *-- "0..*" Продавец
Лоты "1" *-- "0..*" Лот
Сервис_Аутентификации "1" *-- "0..*" User

' Зависимость
Платежный_Сервис --> Продавцы
Платежный_Сервис --> Покупатели

Статистический_Сервис --> Продавцы
Статистический_Сервис --> Покупатели
Статистический_Сервис --> Лоты

' Агрегация
Аукционная_Платформа "1" --o "1" Покупатели
Аукционная_Платформа "1" --o "1" Продавцы
Аукционная_Платформа "1" --o "1" Лоты
Аукционная_Платформа "1" --o "1" Сервис_Аутентификации
Аукционная_Платформа "1" --o "1" Платежный_Сервис

' Ассоциация
Ставка -- Лот
Ставка -- Покупатель
Лот -- Продавец
Отзыв -- Продавец
@enduml