@startuml

left to right direction

state "Окно раздела Лоты"       as lots    {
    "получить_все_лоты()": do / КонтроллерЛотов
}

state "Окно создания лота" as create_lot {
    "создать_лот(Лот)": do / КонтроллерЛотов
}

state "Окно редактирования лота" as edit_lot {
    "определить_победителя(Лот)": do / КонтроллерЛотов
    "получить_лот(Идентификатор)": do / КонтроллерЛотов
    "редактировать_лот(Лот)": do / КонтроллерЛотов
    "добавить_ставку(Ставка)": do / КонтроллерЛотов
}

state "Окно раздела Продавцы"   as sellers {
    "получить_всех_продавцов()": do / КонтроллерПродавцов
}

state "Окно создания продавца" as create_seller {
    "создать_продавца(Продавец)": do / КонтроллерПродавцов
}

state "Окно редактирования продавца" as edit_seller {
    "получить_продавца(Идентификатор)": do / КонтроллерПродавцов
    "редактировать_продавца(Продавец)": do / КонтроллерПродавцов
    "зарегистрировать_отзыв(Отзыв)": do / КонтроллерПродавцов
}

state "Окно раздела Покупатели" as buyers  {
    "получить_всех_покупателей()": do / КонтроллерПокупателей
}

state "Окно создания покупателя" as create_buyer {
    "создать_покупателя(Покупатель)": do / КонтроллерПокупателей
}

state "Окно редактирования покупателя" as edit_buyer {
    "получить_покупателя(Идентификатор)": do / КонтроллерПокупателей
    "редактировать_покупателя(Идентификатор)": do / КонтроллерПокупателей
}

[*] --> lots: Платформа: старт()
lots --> [*]: Вид: выход()

lots --> sellers: ГлавноеОкно: перейти_в_продавцов()
sellers --> lots: ГлавноеОкно: перейти_в_лоты()

lots --> buyers: ГлавноеОкно: перейти_в_покупателей()
buyers --> lots: ГлавноеОкно: перейти_в_лоты()

buyers --> sellers: ГлавноеОкно: перейти_в_продавцов()
sellers --> buyers: ГлавноеОкно: перейти_в_покупателей()

lots --> create_lot: ГлавноеОкно: создать_лот()
lots --> edit_lot: ГлавноеОкно: редакировать_лот()

sellers --> create_seller: ГлавноеОкно: создать_продавца()
sellers --> edit_seller: ГлавноеОкно: редактировать_продавца()

buyers --> create_buyer: ГлавноеОкно: создать_покупателя()
buyers --> edit_buyer: ГлавноеОкно: редактировать_покупателя()

create_lot --> lots: лот создан
edit_lot --> lots: лот отредактирован
create_buyer --> buyers: покупатель создан
edit_buyer --> buyers: покупатель отредактирован
create_seller --> sellers: покупатель создан
edit_seller --> sellers: покупатель отредактирован

@enduml