WINDOW_WIDTH = 800
WINDOW_HEIGHT = 448
FPS = 100

STATE_GAME = "Game"
STATE_MAIN_MENU = "MainMenu"
STATE_LOADING = "Loading"

SDL_VIDEO_CENTERED = "SDL_VIDEO_CENTERED"

GRAVITY = 0.09
FALL_MULTIPLIER = 2.0
SPEED_INCREASE_RATE = 0.038
SPEED_DECREASE_RATE = 0.038
MAX_FASTMOVE_SPEED = 5.0
MAX_MOVE_SPEED = 2.0
MAX_FALL_SPEED = 5.5
JUMP_POWER = 10
LOW_JUMP_MULTIPLIER = 3.0
