version: "3.9"

services:

  postgres:
    build:
      context: .
    environment:
      POSTGRES_DB: "pbz"
      POSTGRES_USER: "pbz"
      POSTGRES_PASSWORD: "pbz"
    ports:
      - "5432:5432"
    expose:
      - 5432
